<a href="https://colab.research.google.com/github/AnshSinghSonkhia/Diploma-in-Data-Analytics-with-Python-NPTEL-Alison-IITR/blob/main/fundamentals-of-python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/content/gapminder-FiveYearData.csv')

In [3]:
df

          country  year         pop continent  lifeExp   gdpPercap
0     Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1     Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2     Afghanistan  1962  10267083.0      Asia   31.997  853.100710
3     Afghanistan  1967  11537966.0      Asia   34.020  836.197138
4     Afghanistan  1972  13079460.0      Asia   36.088  739.981106
...           ...   ...         ...       ...      ...         ...
1699     Zimbabwe  1987   9216418.0    Africa   62.351  706.157306
1700     Zimbabwe  1992  10704340.0    Africa   60.377  693.420786
1701     Zimbabwe  1997  11404948.0    Africa   46.809  792.449960
1702     Zimbabwe  2002  11926563.0    Africa   39.989  672.038623
1703     Zimbabwe  2007  12311143.0    Africa   43.487  469.709298

[1704 rows x 6 columns]

**head()** method shows only the first 5 rows.

In [4]:
print(df.head())

       country  year         pop continent  lifeExp   gdpPercap
0  Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1  Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2  Afghanistan  1962  10267083.0      Asia   31.997  853.100710
3  Afghanistan  1967  11537966.0      Asia   34.020  836.197138
4  Afghanistan  1972  13079460.0      Asia   36.088  739.981106

**shape** shows the shape of data.

In [6]:
print(df.shape)

(1704, 6)

In [7]:
print(df.columns)

Index(['country', 'year', 'pop', 'continent', 'lifeExp', 'gdpPercap'], dtype='object')

In [8]:
print(df.dtypes)

country       object
year           int64
pop          float64
continent     object
lifeExp      float64
gdpPercap    float64
dtype: object

In [10]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1704 non-null   object
 1   year       1704 non-null   int64
 2   pop        1704 non-null   float64
 3   continent  1704 non-null   object
 4   lifeExp    1704 non-null   float64
 5   gdpPercap  1704 non-null   float64
dtypes: float64(3), int64(1), object(2)
memory usage: 80.0+ KB
None

Get only the Country Column

In [16]:
country_df = df['country']
# 1st five rows
country_df.head()

0    Afghanistan
1    Afghanistan
2    Afghanistan
3    Afghanistan
4    Afghanistan
Name: country, dtype: object

In [17]:
# Last five rows
country_df.tail()

1699    Zimbabwe
1700    Zimbabwe
1701    Zimbabwe
1702    Zimbabwe
1703    Zimbabwe
Name: country, dtype: object

Getting more than one column but not all of them.

In [18]:
subset = df[['country', 'continent', 'year']]
subset.head()

       country continent  year
0  Afghanistan      Asia  1952
1  Afghanistan      Asia  1957
2  Afghanistan      Asia  1962
3  Afghanistan      Asia  1967
4  Afghanistan      Asia  1972

Get the 1st Row only

In [19]:
print(df.loc[0])

country      Afghanistan
year                1952
pop            8425333.0
continent           Asia
lifeExp           28.801
gdpPercap     779.445314
Name: 0, dtype: object

Get the 100th Row only

In [20]:
print(df.loc[99])

country      Bangladesh
year               1967
pop          62821884.0
continent          Asia
lifeExp          43.453
gdpPercap    721.186086
Name: 99, dtype: object

**OR**

In [21]:
print(df.loc[100-1])

country      Bangladesh
year               1967
pop          62821884.0
continent          Asia
lifeExp          43.453
gdpPercap    721.186086
Name: 99, dtype: object